### ISSUE TITLE
Use envs to set basic configs

### ISSUE THREAD

**Issue by jtgasper3** [phpcollab/docker#3]
Provide option to declare basic settings (at startup) using env variables

**Comment by mindblender** [comment]
What env variables were you thinking of using?  Would these be used to replace the "setup" screen?

**Comment by jtgasper3** [comment]
Yeah, the basic idea is to optionally bypass the setup page by providing the variables when bootstrapping the container, much like the wordpress image does:

Here's what I'm using so far: https://github.com/phpcollab/docker/blob/ci-test/docker-entrypoint.sh#L156-L159
You can see an example of how they'd be used at: https://github.com/phpcollab/docker/blob/ci-test/README.md in the `stack.yml` file.

If you look at the top of the script there's a few more that are inherited from WordPress. We'll either repurpose the others or remove them.
