### ISSUE TITLE
Install failed: WARNING: unable to establish a database connection to 'db'

### ISSUE THREAD

**Issue by mindblender** [phpcollab/docker#8]
Tried spinning the image up locally and it failed.  I used the example docker-compose.yml code.

**Comment by jtgasper3** [comment]
What failed? Error messages? Log dump?

**Comment by mindblender** [comment]
console output:

db_1         | 2021-02-03T22:32:05.535105Z 0 [Note] Skipping generation of RSA key pair as key files are present in data directory.
db_1         | 2021-02-03T22:32:05.536211Z 0 [Note] Server hostname (bind-address): '*'; port: 3306
db_1         | 2021-02-03T22:32:05.536332Z 0 [Note] IPv6 is available.
db_1         | 2021-02-03T22:32:05.536354Z 0 [Note]   - '::' resolves to '::';
db_1         | 2021-02-03T22:32:05.536375Z 0 [Note] Server socket created on IP: '::'.
db_1         | 2021-02-03T22:32:05.540564Z 0 [Warning] Insecure configuration for --pid-file: Location '/var/run/mysqld' in the path is accessible to all OS users. Consider choosing a different directory.
db_1         | 2021-02-03T22:32:05.550167Z 0 [Note] Event Scheduler: Loaded 0 events
db_1         | 2021-02-03T22:32:05.550573Z 0 [Note] mysqld: ready for connections.
db_1         | Version: '5.7.33'  socket: '/var/run/mysqld/mysqld.sock'  port: 3306  MySQL Community Server (GPL)
db_1         | 2021-02-03T22:32:08.256635Z 2 [Note] Got packets out of order
phpcollab_1  | Welcome to
phpcollab_1  |         _            _____      _ _       _
phpcollab_1  |        | |          / ____|    | | |     | |
phpcollab_1  |   _ __ | |__  _ __ | |     ___ | | | __ _| |__
phpcollab_1  |  | '_ \| '_ \| '_ \| |    / _ \| | |/ _` | '_ \
phpcollab_1  |  | |_) | | | | |_) | |___| (_) | | | (_| | |_) |
phpcollab_1  |  | .__/|_| |_| .__/ \_____\___/|_|_|\__,_|_.__/
phpcollab_1  |  | |         | |
phpcollab_1  |  |_|         |_|
phpcollab_1  | [03-Feb-2021 22:32:11 UTC] Unexpected value
phpcollab_1  | ==================
phpcollab_1  | ❗️ ERROR: Setup
phpcollab_1  | ==================
phpcollab_1  | Exception: Error connecting to database in /var/www/phpcollab/classes/Container.php:124
phpcollab_1  | Stack trace:
phpcollab_1  | #0 /var/www/phpcollab/classes/Installation/Installation.php(89): phpCollab\Container->getPDO()
phpcollab_1  | #1 /var/www/phpcollab/classes/Installation/Installation.php(59): phpCollab\Installation\Installation->testDatabase()
phpcollab_1  | #2 Standard input code(51): phpCollab\Installation\Installation->setup(Array)
phpcollab_1  | #3 {main}
phpcollab_1  |
phpcollab_1  | WARNING: unable to establish a database connection to 'db'
phpcollab_1  |   continuing anyways (which might have unexpected results)
phpcollab_1  |
phpcollab_1  | AH00558: apache2: Could not reliably determine the server's fully qualified domain name, using 172.21.0.3. Set the 'ServerName' directive globally to suppress this message
phpcollab_1  | AH00558: apache2: Could not reliably determine the server's fully qualified domain name, using 172.21.0.3. Set the 'ServerName' directive globally to suppress this message
phpcollab_1  | [Wed Feb 03 22:32:11.405345 2021] [mpm_prefork:notice] [pid 1] AH00163: Apache/2.4.38 (Debian) PHP/7.4.14 configured -- resuming normal operations
phpcollab_1  | [Wed Feb 03 22:32:11.405476 2021] [core:notice] [pid 1] AH00094: Command line: 'apache2 -D FOREGROUND'

**Comment by jtgasper3** [comment]
Oh try the stack.yml file contents. I think I added a env or two there.

**Comment by mindblender** [comment]
I'm doing some additional testing.

**Comment by mindblender** [comment]
I was able to connect to the DB with a test script and create a table.  not sure why phpCollab failed.  Maybe a timing issue?

**Comment by mindblender** [comment]
used the stack.yml and it worked.  I'll update the README :)
